#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'helper','console_scripts','helper'
__requires__ = 'helper'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('helper', 'console_scripts', 'helper')()
    )
